# Generated by Django 4.2 on 2024-10-04 11:48

from django.db import migrations, models
import django.db.models.deletion
import shop2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('shop3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='instructor')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='menuitem')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='', max_length=100)),
                ('contents', models.TextField()),
                ('start_date_time', models.DateTimeField(validators=[shop2.models.validate_time])),
                ('end_date_time', models.DateTimeField(validators=[shop2.models.validate_time])),
                ('location', models.CharField(max_length=100)),
                ('quota', models.IntegerField(default=0)),
                ('filled_place', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(max_length=100)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructors', to='shop2.instructor')),
                ('menu_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menuitems', to='shop2.menuitem')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.product')),
                ('studio_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='studios', to='shop3.studio')),
            ],
        ),
    ]
