# Generated by Django 4.2 on 2024-10-04 11:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Cake_Sizes', models.CharField(choices=[('12cm', '12cm'), ('18cm', '18cm'), ('22cm', '22cm'), ('28cm', '28cm')], max_length=50)),
                ('Cake_Weight', models.CharField(choices=[('400g', '400g'), ('850g', '850g'), ('1.2kg', '1.2kg'), ('1.8kg', '1.8kg')], max_length=50)),
                ('Cake_Desc', models.CharField(choices=[('For 3 - 4 persons', 'For 3 - 4 persons'), ('For 8 - 10 persons', 'For 8 - 10 persons'), ('For 10 - 12 persons', 'For 10 - 12 persons'), ('For 18 - 20 persons', 'For 18 - 20 persons')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('OrderingDT', models.DateTimeField(default=django.utils.timezone.now)),
                ('OrderingConfirm', models.BooleanField(default=False)),
                ('ContactPerson', models.CharField(max_length=50, null=True)),
                ('ContactNumber', models.CharField(max_length=50)),
                ('ContactEmail', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Qty', models.IntegerField(blank=True, default=0, null=True)),
                ('CakeSize', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('CakeWeight', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('CakeDesc', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('CakePrice', models.IntegerField(blank=True, default=0, null=True)),
                ('PickupDelivery', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('PickupDeliveryTime', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('PickupDeliveryDate', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('DeliveryAddr', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('DeliveryCharges', models.IntegerField(blank=True, default=0, null=True)),
                ('OrderAmount', models.IntegerField(blank=True, default=0, null=True)),
                ('Category_id', models.IntegerField(blank=True, default=0, null=True)),
                ('Product_id', models.IntegerField(blank=True, default=0, null=True)),
                ('Session_Key', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allergen', models.TextField(blank=True)),
                ('First_size', models.CharField(choices=[('12cm', '12cm'), ('18cm', '18cm'), ('22cm', '22cm'), ('28cm', '28cm')], default='12cm', max_length=50)),
                ('First_weight', models.CharField(choices=[('400g', '400g'), ('850g', '850g'), ('1.2kg', '1.2kg'), ('1.8kg', '1.8kg')], default='400g', max_length=50)),
                ('First_desc', models.CharField(choices=[('For 3 - 4 persons', 'For 3 - 4 persons'), ('For 8 - 10 persons', 'For 8 - 10 persons'), ('For 10 - 12 persons', 'For 10 - 12 persons'), ('For 18 - 20 persons', 'For 18 - 20 persons')], default='For 3 - 4 persons', max_length=50)),
                ('First_price', models.IntegerField()),
                ('Second_size', models.CharField(choices=[('12cm', '12cm'), ('18cm', '18cm'), ('22cm', '22cm'), ('28cm', '28cm')], default='18cm', max_length=50)),
                ('Second_weight', models.CharField(choices=[('400g', '400g'), ('850g', '850g'), ('1.2kg', '1.2kg'), ('1.8kg', '1.8kg')], default='850g', max_length=50)),
                ('Second_desc', models.CharField(choices=[('For 3 - 4 persons', 'For 3 - 4 persons'), ('For 8 - 10 persons', 'For 8 - 10 persons'), ('For 10 - 12 persons', 'For 10 - 12 persons'), ('For 18 - 20 persons', 'For 18 - 20 persons')], default='For 8 - 10 persons', max_length=50)),
                ('Second_price', models.IntegerField()),
                ('Third_size', models.CharField(choices=[('12cm', '12cm'), ('18cm', '18cm'), ('22cm', '22cm'), ('28cm', '28cm')], default='22cm', max_length=50)),
                ('Third_weight', models.CharField(choices=[('400g', '400g'), ('850g', '850g'), ('1.2kg', '1.2kg'), ('1.8kg', '1.8kg')], default='1.2kg', max_length=50)),
                ('Third_desc', models.CharField(choices=[('For 3 - 4 persons', 'For 3 - 4 persons'), ('For 8 - 10 persons', 'For 8 - 10 persons'), ('For 10 - 12 persons', 'For 10 - 12 persons'), ('For 18 - 20 persons', 'For 18 - 20 persons')], default='For 10 - 12 persons', max_length=50)),
                ('Third_price', models.IntegerField()),
                ('Fourth_size', models.CharField(choices=[('12cm', '12cm'), ('18cm', '18cm'), ('22cm', '22cm'), ('28cm', '28cm')], default='28cm', max_length=50)),
                ('Fourth_weight', models.CharField(choices=[('400g', '400g'), ('850g', '850g'), ('1.2kg', '1.2kg'), ('1.8kg', '1.8kg')], default='1.8kg', max_length=50)),
                ('Fourth_desc', models.CharField(choices=[('For 3 - 4 persons', 'For 3 - 4 persons'), ('For 8 - 10 persons', 'For 8 - 10 persons'), ('For 10 - 12 persons', 'For 10 - 12 persons'), ('For 18 - 20 persons', 'For 18 - 20 persons')], default='For 18 - 20 persons', max_length=50)),
                ('Fourth_price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product')),
            ],
        ),
    ]
