# Generated by Django 4.2 on 2024-10-07 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('shop1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='product_id',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='product_detail', to='shop.product'),
            preserve_default=False,
        ),
    ]
