# Generated by Django 4.2 on 2024-10-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0002_remove_productdetail_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='name',
            field=models.CharField(blank=True, default='no name', max_length=50, null=True),
        ),
    ]
