# Generated by Django 4.2 on 2024-10-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0003_productdetail_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ordering',
        ),
    ]
